### ISSUE TITLE
[FEATURE] Align the new player properly in fullscreen

### ISSUE THREAD

**Issue by Lunahria** [vod-friends/lirik.tv#14]
This was okay with the YouTube player but it's a little off with the new one.

![JnTI9mqSqqta0OTZ](https://user-images.githubusercontent.com/32708029/138619211-8bc3618b-b248-4ad1-8180-67e287f74695.png)

**Comment by Daniele122898** [comment]
Do you perhaps have a 16:10 screen?

**Comment by Lunahria** [comment]
Nope, 16:9 as the screenshot's aspect ratio. I'm using Firefox but I think that giant scrollbar might have given it away already.

**Comment by Lunahria** [comment]
I see you are still using YouTube sometimes, here's a reference if it helps with anything.

![rgKjYMXfdeeRxsPT](https://user-images.githubusercontent.com/32708029/138756203-692a5657-e8e5-4cb3-b1eb-1f72f1931241.png)

**Comment by Daniele122898** [comment]
The next thing on the todo, once i have enough time to do it, would be to completely overhaul the custom player and write my own. so i think i wont fix it for now since it'll get thrown away anyway. Once the new player is in place, for which i cannot give an ETA since my studies and contract work are a ton of workload already, i'll see here again if you still have any issues. so i wont close this issue for now.

**Comment by jonrainier** [comment]
Added with current player.
